import { XP_TABLE, MAX_LEVEL } from '../woc/src/sim/types.ts';
import { GROUP_XP_BONUS } from '../woc/src/sim/data.ts';
import * as fs from 'node:fs';

const OUT = process.argv[2] || '/tmp/gen/combat.md';
const L: string[] = [];
L.push(`# How combat works`);
L.push('');
L.push(`The exact maths the game runs, pulled straight from its source — so the bestiary and gear numbers add up.`);
L.push('');
L.push(`## Mob stats by level`);
L.push('');
L.push(`A mob's stats scale linearly from its template, per level **L**:`);
L.push('');
L.push('```');
L.push('Health = round((hpBase + hpPerLevel·(L−1)) × eliteMult)');
L.push('Damage = (dmgBase + dmgPerLevel·(L−1)) × eliteMult   (swing 0.8×–1.25×)');
L.push('Armor  = round(armorPerLevel·(L−1))');
L.push('```');
L.push('');
L.push(`**Elite** mobs use a multiplier of **2.3× health** and **1.5× damage** (and double XP). Normal mobs are 1×.`);
L.push('');
L.push(`## Armor & physical mitigation`);
L.push('');
L.push(`Armor reduces *physical* damage only (spells ignore it). Against an attacker of level **L**:`);
L.push('');
L.push('```');
L.push('damage reduction = min(0.75, armor / (armor + 85·L + 400))');
L.push('```');
L.push('');
L.push(`So mitigation is capped at **75%**, and the same armor is worth less against higher-level attackers. This is the "% mitigation" shown in the bestiary.`);
L.push('');
L.push(`## Health from Stamina`);
L.push('');
L.push(`Stamina on gear adds to your health pool: the first 20 points give **+1 HP each**, and every point beyond 20 gives **+10 HP**:`);
L.push('');
L.push('```');
L.push('bonusHP = min(sta, 20) + max(0, sta − 20) × 10');
L.push('```');
L.push('');
L.push(`## Experience curve`);
L.push('');
L.push(`XP needed to clear each level (level cap is **${MAX_LEVEL}**):`);
L.push('');
L.push(`| Level | XP to next | Cumulative |`);
L.push(`|---:|---:|---:|`);
let cum = 0;
for (let i = 0; i < XP_TABLE.length; i++) { cum += XP_TABLE[i]; L.push(`| ${i + 1} | ${XP_TABLE[i].toLocaleString()} | ${cum.toLocaleString()} |`); }
L.push('');
L.push(`## Group XP`);
L.push('');
L.push(`Killing in a party splits XP but adds a bonus that makes grouping efficient. Multiplier by party size:`);
L.push('');
L.push(`| Players | XP multiplier |`);
L.push(`|---:|---:|`);
GROUP_XP_BONUS.forEach((m: number, i: number) => L.push(`| ${i + 1} | ${m}× |`));
L.push('');
L.push(`_Party members must be within ~80 yards to share a kill's XP and credit._`);
L.push('');

fs.mkdirSync(OUT.replace(/[/\\][^/\\]+$/, '') || '.', { recursive: true });
fs.writeFileSync(OUT, L.join('\n'));
console.log(`wrote combat reference (${XP_TABLE.length} levels)`);
